# Generated by Django 5.2.17 on 2026-09-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_venue_cancha_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='cancha',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='courts.venue', verbose_name='Establecimiento'),
        ),
    ]
