# Generated by Django 5.2.17 on 2026-09-13 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_remove_cancha_ubicacion_alter_cancha_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='duracion_slot_minutos',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Duración del slot en minutos'),
        ),
        migrations.AddField(
            model_name='venue',
            name='porcentaje_abono',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de abono'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
    ]
