# Generated by Django 5.2.17 on 2026-09-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_horario_duracion_slot_minutos_venue_porcentaje_abono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='courts/', verbose_name='Imagen de la cancha'),
        ),
        migrations.AddField(
            model_name='venue',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='venues/', verbose_name='Imagen del establecimiento'),
        ),
    ]
