# Generated by Django 5.2.17 on 2026-09-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
