# Generated by Django 5.2.17 on 2026-09-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='abono_requerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hold_expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='origen_datos',
            field=models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('HISTORICAL_REAL', 'Histórico real'), ('SYSTEM', 'Sistema')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
